# Changes here will be overwritten by Copier
_commit: v0.3.7
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
description: "@fohte's shared Lefthook configuration"
is_public: true
project_name: lefthook-config
release_type: simple
subpackages: []
type: base
use_release_please: true
