# Changes here will be overwritten by Copier
_commit: v0.1.20
_src_path: https://github.com/fohte/generic-boilerplate
description: "@fohte's shared Lefthook configuration"
is_public: true
release_type: simple
type: base
use_release_please: true
