[tools]
lefthook = "2.1.4"

# lefthook hooks
<<<<<<< before updating
actionlint = "1.7.11"
pinact = "3.9.0"
node = "24.14.0"
=======
actionlint = "1.7.12"
node = "24.14.1"
pinact = "3.9.0"
>>>>>>> after updating
"github:fohte/basefmt" = "0.1.0"
"npm:@commitlint/cli" = "20.5.0"
"npm:prettier" = "3.8.1"
shellcheck = "0.11.0"
shfmt = "3.13.0"
