# Base configuration for language-agnostic hooks
# These hooks can be used across any project regardless of programming language

pre-commit:
  commands:
    end-of-file-fixer:
      run: bash .lefthook/scripts/end-of-file-fixer.sh {staged_files}
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"

    trailing-whitespace:
      run: bash .lefthook/scripts/trailing-whitespace.sh {staged_files}
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"
      # For markdown files, preserve line breaks (two spaces at end of line)
      env:
        MARKDOWN_LINEBREAK_EXT: "md,mdx"
