# Base configuration for language-agnostic hooks
# These hooks can be used across any project regardless of programming language

pre-commit:
  commands:
    format:
      # Simple formatting fixes: remove trailing whitespace and ensure final newline
      run: ./scripts/format-fix.sh {staged_files} && git add {staged_files}
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"

    shfmt:
      # Format shell scripts (both with and without extensions)
      run: |
        for f in {staged_files}; do
          # Check if file has .sh or .bash extension
          if [[ "$f" == *.sh ]] || [[ "$f" == *.bash ]]; then
            shfmt -w "$f" && git add "$f"
          # Check if file without extension has shell shebang
          elif [[ ! "$f" == *.* ]] && head -n1 "$f" 2>/dev/null | grep -q '^#!/.*\(bash\|sh\)'; then
            shfmt -w "$f" && git add "$f"
          fi
        done
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"

    shellcheck:
      # Lint shell scripts (both with and without extensions)
      run: |
        for f in {staged_files}; do
          # Check if file has .sh or .bash extension
          if [[ "$f" == *.sh ]] || [[ "$f" == *.bash ]]; then
            shellcheck "$f"
          # Check if file without extension has shell shebang
          elif [[ ! "$f" == *.* ]] && head -n1 "$f" 2>/dev/null | grep -q '^#!/.*\(bash\|sh\)'; then
            shellcheck "$f"
          fi
        done
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"
