# Base configuration for language-agnostic hooks
# These hooks can be used across any project regardless of programming language

pre-commit:
  commands:
    editorconfig:
      # Fix files according to .editorconfig settings using pure shell script
      # No external dependencies required (no Node.js, bun, etc.)
      run: |
        # Use the POSIX-compliant editorconfig implementation
        script_path="./scripts/editorconfig-fix.sh"
        
        # Check if script exists locally
        if [ ! -f "$script_path" ]; then
          # Try to download it from the repository
          echo "Downloading editorconfig-fix.sh..."
          mkdir -p ./scripts
          curl -sL https://raw.githubusercontent.com/fohte/lefthook-config/main/scripts/editorconfig-fix.sh -o "$script_path"
          chmod +x "$script_path"
        fi
        
        if [ -f "$script_path" ]; then
          # Process each staged file
          for file in {staged_files}; do
            if [ -f "$file" ]; then
              "$script_path" "$file"
            fi
          done
          # Re-add modified files
          git add {staged_files}
        else
          echo "Warning: Could not find or download editorconfig-fix.sh"
          exit 1
        fi
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"