# Base configuration for language-agnostic hooks
# These hooks can be used across any project regardless of programming language

pre-commit:
  commands:
    format:
      # Simple formatting fixes: remove trailing whitespace and ensure final newline
      run: basefmt {staged_files} && git add {staged_files}
      glob: "*"

    shellcheck:
      files: git diff --cached --name-only --diff-filter=ACMR | xargs file | grep -E 'shell|bash' | cut -d':' -f1
      run: mise x shellcheck -- shellcheck {files}

    shfmt:
      files: git diff --cached --name-only --diff-filter=ACMR | xargs file | grep -E 'shell|bash' | cut -d':' -f1
      run: mise x shfmt -- shfmt -w {files} && git add {files}
