# Base configuration for language-agnostic hooks
# These hooks can be used across any project regardless of programming language

pre-commit:
  commands:
    format:
      # Simple formatting fixes: remove trailing whitespace and ensure final newline
      run: basefmt {staged_files} && git add {staged_files}
      glob: '*'

    prettier:
      run: |
        if [ -f bun.lockb ] || [ -f bun.lock ]; then
          runner="bun x"
        elif [ -f pnpm-lock.yaml ]; then
          runner="pnpm exec"
        elif [ -f package.json ]; then
          runner="npx"
        else
          runner="mise x --"
        fi
        $runner prettier --write --ignore-unknown {staged_files} && git add {staged_files}

    shellcheck:
      files: &shell-files git diff --cached --name-only -z --diff-filter=ACMR | xargs -0 file --separator '%%' | grep -E '%%.*(shell|bash)' | sed 's/%%.*//'
      run: mise x shellcheck -- shellcheck '{files}'

    shfmt:
      files: *shell-files
      run: mise x shfmt -- shfmt -w '{files}' && git add '{files}'
