# Base configuration for language-agnostic hooks
# These hooks can be used across any project regardless of programming language

pre-commit:
  commands:
    format:
      # Simple formatting fixes: remove trailing whitespace and ensure final newline
      run: ./scripts/format-fix.sh {staged_files} && git add {staged_files}
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"

    shfmt:
      # Format shell scripts (detected by file command)
      run: |
        printf '%s\n' {staged_files} | \
        xargs -I {} sh -c 'file --mime-type "{}" | grep -q "text/x-shellscript" && echo "{}"' | \
        xargs sh -c 'if [ $# -gt 0 ]; then shfmt -w "$@" && git add "$@"; fi' _
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"

    shellcheck:
      # Lint shell scripts (detected by file command)
      run: |
        printf '%s\n' {staged_files} | \
        xargs -I {} sh -c 'file --mime-type "{}" | grep -q "text/x-shellscript" && echo "{}"' | \
        xargs sh -c 'if [ $# -gt 0 ]; then shellcheck "$@"; fi' _
      glob: "*"
      exclude: "*.{png,jpg,jpeg,gif,ico,pdf,svg,woff,woff2,ttf,eot}"
