# Base configuration for language-agnostic hooks
# These hooks can be used across any project regardless of programming language

pre-commit:
  commands:
    format:
      # Simple formatting fixes: remove trailing whitespace and ensure final newline
      run: basefmt {staged_files} && git add {staged_files}
      glob: '*'

    prettier:
      run: |
        if [ -f bun.lockb ] || [ -f bun.lock ]; then
          runner="bun x"
        elif [ -f pnpm-lock.yaml ]; then
          runner="pnpm exec"
        elif [ -f package.json ]; then
          runner="npx"
        else
          runner="mise x --"
        fi
        $runner prettier --write --ignore-unknown {staged_files} && git add {staged_files}

    shellcheck:
      files: git diff --cached --name-only --diff-filter=ACMR | xargs file | grep -E 'shell|bash' | cut -d':' -f1
      run: mise x shellcheck -- shellcheck {files}

    shfmt:
      files: git diff --cached --name-only --diff-filter=ACMR | xargs file | grep -E 'shell|bash' | cut -d':' -f1
      run: mise x shfmt -- shfmt -w {files} && git add {files}
