name: Test

on:
  push:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Run lefthook
        id: lefthook
        run: |
          lefthook run pre-commit --all-files

      - name: Commit formatted files
        if: ${{ !cancelled() }}
        uses: suzuki-shunsuke/commit-action@v0.0.8
        with:
          commit_message: 'style: auto-format'
          workflow: deny
          github_token: ${{ steps.app-token.outputs.token }}

  test-format-script:
    runs-on: ubuntu-latest
    name: Test format-fix.sh script

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Run bats tests for format-fix.sh
        run: |
          bats tests/format-fix.bats
